### ISSUE TITLE
allow input from jack audio (jackd)

### ISSUE THREAD

**Issue by G-9999** [vovoid/vsxu#155]
I use Jack exclusively and would prefer this over Pulse for better audio routing / source selection and mixing.

**Comment by alown** [comment]
Apologies for this necrobump, but this looks like the best place to leave a note for anybody else wanting to make JACK work with vsxu (tested against aea3f38779bb8c8d85b6996c834241a3a6bfdd7a).

The defines in `plugins/src/sound.rtaudio/{CMakeLists.txt,main_sound.rtaudio.cpp}` for `__LINUX_JACK__` should be changed to `__UNIX_JACK__` to match RtAudio.
If your jack server is running at anything other than 44.1kHz, the sampleRate variable defined in `rtaudio_record.h` will also need to be changed, otherwise RtAudio will fail to start the backend.

Perhaps I should send in a patch fixing this/exposing a sample rate flag?

**Comment by neurofpga** [comment]
> Apologies for this necrobump, but this looks like the best place to leave a note for anybody else wanting to make JACK work with vsxu (tested against [aea3f38](https://github.com/vovoid/vsxu/commit/aea3f38779bb8c8d85b6996c834241a3a6bfdd7a)).
> 
> The defines in `plugins/src/sound.rtaudio/{CMakeLists.txt,main_sound.rtaudio.cpp}` for `__LINUX_JACK__` should be changed to `__UNIX_JACK__` to match RtAudio.
> If your jack server is running at anything other than 44.1kHz, the sampleRate variable defined in `rtaudio_record.h` will also need to be changed, otherwise RtAudio will fail to start the backend.

Player (vsxu_player,  6e556ea ) is still not reacting to Jack after your changes. What may be missing? Or should I add special arguments during launch? Thanks!

**Comment by alown** [comment]
> Player (vsxu_player, [6e556ea](https://github.com/vovoid/vsxu/commit/6e556ea8a222ae41d36ea8e98a9d4415133be539) ) is still not reacting to Jack after your changes. What may be missing? Or should I add special arguments during launch? Thanks!

Unfortunately, we are going to need a bit more information about your setup to be able to help you with this, a few "obvious" things to check:
- 6e556ea is a lot more recent than aea3f38, have you tried the same thing with aea3f38 in case something more recent has made this more complicated?
- Are you running against JACK 1 or 2? (`jackd --version`)
- Is the version of vsxu you are running actually built with JACK support (do you have the log from cmake?)
- Have you tried explicitly running with `vsxu_player -sound_type_jack` to force rtaudio to use JACK - as it should default to pulseaudio if it was built with support for it...
- Does `jack_lsp` (or another patchbay) show the ports from vsxu?
- Do you get any notable messages from rtaudio on stdout/stderr?
etc.

**Comment by DJPlaya** [comment]
Since 05404800 (0.6.3), it is possible to select the Audio Input in the Launcher or using -audio_input_device ID

This Issue should be closed then
