### ISSUE TITLE
GLSL out of date or incomplete

### ISSUE THREAD

**Issue by SoraHjort** [vovoid/vsxu#173]
Just about everytime I load a GLSL shader into the GLSL loader, I get errors such as "Undefined Variable" for tags such as iResolution, iGlobalTime, and so on. Somethings like iMouse being excluded can make sense due to the application of VSXu. Then again, someone could use iMouse to setup a visual to shift between multiple sub-visuals by the position of the mouse.

**Comment by jaw** [comment]
First, with a bug report like this - a source example might help... 

Only reason for undefined variables in GLSL is if you do not declare them. 

Also, AFAIK - iResolution, iGlobalTime and iMouse are not part of the GLSL standard and is probably due to you copying shaders from some other program which prepends the source code with these variables and declares them as Uniforms which is what you should be doing. 

With a float uniform for instance - you can supply your shader with time, or resolution, or anything. 

VSXu declares GLSL Uniforms as regular module parameters so you can hook them to whatever you want, thus there is no need for any special vendor-specific variables which I'm guessing is what is causing issues for you.

BTW mouse, keyboard and gamepad support is present in our development branch which will be released later this year.

**Comment by SoraHjort** [comment]
Maybe it's a WebGL specific thing then. But it seems like where ever I go for examples they include these i(x) calls. Whether it's from sites like ShaderToy.com (A good site of examples of what I was running into) to random blogs talking about GLSL shaders.

So I suppose it is less an issue of whether or not VSXu is up to date on GLSL, but an issue that everyone else is using a specfic offshoot of GLSL. Which actually now that I think about, sucks. Since so few are writing in regular GLSL it means getting examples or help is harder to come by. 
Sorry for the waste of time =\

**Comment by jaw** [comment]
iResolution is shader toy specific.

There are some good books.
https://www.opengl.org/documentation/books/#book_the_opengl_shading_language

I learnt from the "Orange Book" but that seems to be obsolete/outdated now.

And the specification: https://www.khronos.org/files/opengl44-quick-reference-card.pdf

VSXu is mostly GL 2.x though, but you can make shaders with any version of GLSL despite this AFAIK.
