### ISSUE TITLE
VLC plugin

### ISSUE THREAD

**Issue by cwilling** [vovoid/vsxu#188]
Recent versions of VSXu are no longer compatible with VLC  - there is (at least) no libvsxu.pc, no libvsxu.so, no vsx_manager.h etc.

I see you were one author of the original, now not working, vlc plugin vsxu.cpp. Do you have plans to update the vlc's plugin to accept the new vsxu?

**Comment by jaw** [comment]
No, VLC resets the visual plugin every time a new song is played which destroys the state of the visuals in VSXu who some of them evolve over several minutes of use, so VLC turned out to be a wasted effort for us. Also, reloading them every time is hurtful for performance. Thus, it's pretty broken, and I don't see any reason to support it unless this behaviour is changed, and last I heard it was not even possible.

In order to successfully incorporate visuals into a music player, it has to be designed for it, not an afterthought. Sadly no player currently in active development meets our criteria.
